### ISSUE TITLE
Feature request: Custom image center

### ISSUE THREAD

**Issue by egasimus** [jazzband/sorl-thumbnail#104]
Another feature that I think would be helpful (although probably not easy to implement): being able to specify one point that should be as close to the centre of the cropped thumbnail as possible.

Depicted here:
http://img88.imageshack.us/img88/8151/kittehc.png

Being able to graphically pick one in the admin panel would require some quite involved JavaScript magic, but how about two fields (X and Y coordinates) that can take either pixels or percentages?

**Comment by camilonova** [comment]
This issue should be outdated by now. I'm closing it.
