### ISSUE TITLE
thumbnail are not using settings.FILE_UPLOAD_PERMISSIONS permissions

### ISSUE THREAD

**Issue by cocobuster** [jazzband/sorl-thumbnail#115]
When thumbnails are created they should at least have the same permissions as the original file, 
or consider settings.FILE_UPLOAD_PERMISSIONS.

The issue occurs when managing the thumbnails with scripts I am unable to modify the files as
group only have READ permissions by default.

**Comment by camilonova** [comment]
This issue should be outdated by now. I'm closing it.
