### ISSUE TITLE
Transparency of generated thumbnail images

### ISSUE THREAD

**Issue by sergey-aleshin** [jazzband/sorl-thumbnail#12]
Hi!

Is it possible to preserve transparency in thumbnails? I.e. thumbnail of transparent image have to be transparent too (for PNG).

**Comment by jplehmann** [comment]
I'm confused because I'm still having the same problem.  My transparent images are getting a black background, not white?

**Comment by SalahAdDin** [comment]
Ah, will be great that you put this informatión in the docs :D
