### ISSUE TITLE
[Feature Request] - Add filter for thumbnail generation based on presets

### ISSUE THREAD

**Issue by levynir** [jazzband/sorl-thumbnail#163]
For more consistant html I suggest you can add something like this.:

<pre><code>
@register.filter(name='thumb')
def thumb(value, preset):
    '''
    Template filter for fast template generation using image persets so we 
    can have consistent image sizes across the size. 
    
    Input: 
        value: an image field, file field or URL string
        preset: a name of preset to use for this image (defined in settings.py) 
        
    Exmaple:
        &lt;img src='{{img.image|thumb:"large"}}' alt='{{img.name|default:"Image"}}' width="100%"&gt;
    '''
    presets = settings.IMAGE_PRESETS + \
               {
               'default' : {'size': '1920','colorspace': 'RGB', 'quality': 95, 'crop': 'noop', 'upscale':False, } 
               }
    options = presets[preset] 
    return get_thumbnail(value, options.pop('size'), **options).url
</code></pre>

**Comment by jjdelc** [comment]
I made this to address that: https://github.com/jjdelc/sorl-defined-thumbnails

**Comment by SalahAdDin** [comment]
@jjdelc These package could be included in this package.

**Comment by SalahAdDin** [comment]
@levynir Why did you close this issue?

**Comment by levynir** [comment]
@SalahAdDin this is a 3-4 years old feature request with an external workaround. I don't think anyone would implement this in the next 3 years.. no need to spam the repo with irrelevant feature requests
