### ISSUE TITLE
Invalid block tag: 'endthumbnail', expected 'empty' or 'endfor'

### ISSUE THREAD

**Issue by deronsizemore** [jazzband/sorl-thumbnail#184]
I'm getting this error message when using sorl-thumbnail in my template. Here's the code I'm using (basically just copied and pasted from the docs:

   {% thumbnail post.image "100x100" crop="center" as im %}
   img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
   {% endthumbnail %}

Any pointers as to what I'm doing wrong here? I've seen some topics on google related to this that talk about being on the wrong version of sorl-thumbnail and that the endthumbnail tag isn't valid on older versions, but I did a pip install which I assume gives me the most recent version? What am I doing wrong?

Thanks

Note: I left out the "<" and ">" on the img tag. I couldn't get GitHub to display it as code and it was parsing it as an image, thus hiding my code.

**Comment by Narengowda** [comment]
The problem can also be with loading template tags.

I was doing `{% load thumbnail %}` in base html.
When I call below code in inherited html, got same error.

    {% thumbnail service_type.pic.image "100x100" crop="center" as im %}
       <img .....>
    {% endthumbnail %} 

See this discussion [about loading template tags in base.html][1]


  [1]: http://stackoverflow.com/questions/20560222/is-it-possible-to-load-a-custom-template-tag-in-base-and-use-it-in-extented-temp

**Comment by Elger9** [comment]
If you do not want to give up easy-thumbnails because, for example, you use it elsewhere, then instead of

{% load thumbnail %}

use: 

{% load sorl_thumbnail %}
