### ISSUE TITLE
Clearing / Redoing cache?

### ISSUE THREAD

**Issue by deronsizemore** [jazzband/sorl-thumbnail#208]
I'm using Django Userena for my profiles. On each new submission, I'm displaying a small thumbnail with sorl-thumbnail of the submitter's profile image. When the user doesn't upload an image, it defaults to a generic image. I changed the generic image tonight to something else, yet the old image still showed on each entry. I went into my MEDIA_ROOT directory and deleted the contents of the "cache" directory and now just a broken image is showing. Is there a way to redo (for lack of a better word?) the cache so that it re-generates images? Hope that makes sense. Here's the code I'm using to generate the image:

```
{% with 'http://'|add:request.get_host|add:post.submitter.get_profile.get_mugshot_url as path %}
{% thumbnail path '20x20' crop='center' as im %}
<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% endthumbnail %}
{% endwith %}
```

**Comment by vartagg** [comment]
@relekang Thank you very much for your explanation. In my case, a cache not cleared because I'm saving a name of uploading images as is.
