### ISSUE TITLE
Use with django-cumulus results in very slow page load

### ISSUE THREAD

**Issue by elsmorian** [jazzband/sorl-thumbnail#234]
I'm using sorl-thumbnail together with django-cumulus, and specifying `DEFAULT_FILE_STORAGE = 'cumulus.storage.SwiftclientStorage'` in my settings, however when this is used page loads become very slow and also vary to a huge degree.

It is my understanding that sorl hits the (KV-store or cached DB) to check for the existence of thumbnails, and assumes if they are there they exist on the storage, and returns the URL. However the behaviour as described above leads me to believe sorl is actually hitting the storage as well / instead, might this be happening?

The image i'm trying to thumbnail is a standard ImageField. Setting the file storage to the default local filesystem storage fixes the issue, so it is not the speed of the thumbnail URL lookup from the DB. Keeping the cloud-storage in but removing the thumbnailing from the template also results in a fast page load (and the profile in-broswer of the page load shows the slowness is not the browser getting the image from the cloud storage).

So the only thing I can think of is sorl is infact hitting the cloud-storage when it tries to find the thumbnail - is this correct? Am I not setting something correctly somewhere- do you have to set a font-check-storage setting that I have managed to miss?

**Comment by camilonova** [comment]
This issue should be outdated by now. I'm closing it.
