### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by vovkd** [jazzband/sorl-thumbnail#242]
When generating thumbnail for a small image (1x54 px) sorl raises ZeroDivisionError. For some reason PIL and pgmagic thinks that image has 0x54 dimensions. Even if the problem with an image i think calculate_scaling_factor must prevent such situations.

Exception Type: ZeroDivisionError
Exception Value:    integer division or modulo by zero

sorl/thumbnail/engines/base.py in calculate_scaling_factor

---

...
54     factors = (geometry[0] / x_image, geometry[1] / y_image) 
...

y_image 16
geometry    (16, 16)
self    <sorl.thumbnail.engines.pil_engine.Engine object at 0xacd1ccc>
crop    False
x_image 0

options 
{'colorspace': 'RGB',
 'crop': False,
 'cropbox': None,
 'format': 'JPEG',
 'image_info': {'Software': 'Adobe ImageReady', 'gamma': 0.45},
 'padding': False,
 'padding_color': '#ffffff',
 'quality': 95,
 'rounded': None,
 'upscale': True}

**Comment by philippze** [comment]
I've experienced the same error. It disappeared after I made an update from Pillow==3.0.0 to Pillow==4.0.0.
