### ISSUE TITLE
Optional WebP images for browsers that support it

### ISSUE THREAD

**Issue by don-mums** [jazzband/sorl-thumbnail#267]
It would be really cool to serve webp images to browsers that support it. I need transparent images on my site and that's why I use png. But it increases size of a page to more than 1MB which is really too much. With webp it would be a lot less because it would be possible to use looseless  compression.

Support of this image format can be determined by looking at accept http header.

**Comment by Flimm** [comment]
Thanks to this pull request (#460), it is now possible to use Webp, like this:

    <picture>
      {% thumbnail model.image "200x200" format="WEBP" as im %}
        <source srcset="{{ im.url }}" type="image/webp">
      {% endthumbnail %}
      {% thumbnail model.image "200x200" format="JPEG" as im %}
        <source srcset="{{ im.url }}" type="image/jpeg">
        <img src="{{ im.url }}" alt="">
      {% endthumbnail %}
    </picture>

It would be really useful if the mimetype of the image could be accessed like this:

    {% thumbnail model.image "200x200" as im %}
      <source srcset="{{ im.url }}" type="{{ im.mime }}">
    {% endthumbnail %}

**Comment by SalahAdDin** [comment]
Good for documentation.
