### ISSUE TITLE
Division by zero on smart crop

### ISSUE THREAD

**Issue by awidgery** [jazzband/sorl-thumbnail#350]
I'm getting a `float division by zero` error here:

```
sorl/thumbnail/engines/pil_engine.py in _get_image_entropy, line 239
```

I'm calling it using:

```
{% thumbnail comment.user.profile.avatar_image "30x30" crop="smart" as im %}
```

This happens on some images and not others. The image that's causing me issues is this one:

https://www.dropbox.com/s/m5e79cvk53ujs7b/Chelsea_physic_garden.jpg?dl=0

From a brief bit of digging the code is:

```
def _get_image_entropy(self, image):
    """calculate the entropy of an image"""
    hist = image.histogram()
    hist_size = sum(hist)
    print hist_size
    hist = [float(h) / hist_size for h in hist]
    return -sum([p * math.log(p, 2) for p in hist if p != 0])
```

`print hist_size` gives a zero in the console - hence the error. We need some sort of `try`/`except` on this calculation, but I'm not sure what the `except` should be!

**Comment by awidgery** [comment]
Should have said I'm using `sorl-thumbnail==11.12.1b`

**Comment by Arti3DPlayer** [comment]
Have the same bug

**Comment by mrkre** [comment]
Same bug is reproduced when calling `get_thumbnail` from `sorl.thumbnail` even when crop='center' is used

**Comment by lampslave** [comment]
Try with pillow==3.1.0. See #429.

**Comment by mrkre** [comment]
@lampslave Thanks. Solves the issue.
