### ISSUE TITLE
Feature: responsive margin

### ISSUE THREAD

**Issue by SalahAdDin** [jazzband/sorl-thumbnail#365]
I like this lib; now i'm using for a responsive web page, and i need put automaticly margin for slider images, but, the margin is ever in px, i think that will be better put in rem, more responsive.

**Comment by haakenlid** [comment]
`rem` is not known until the image is rendered in a html document in a client (web browser). So you have an example of what you want to do?

**Comment by SalahAdDin** [comment]
Now, i forget this issue but, i think, will be useful put a rem margin for more responsive rendering.

**Comment by camilonova** [comment]
This issue should be outdated by now. I'm closing it.
