### ISSUE TITLE
Test suite failure: pgmagick._pgmagick.get_blob_data raises UnicodeDecodeError in python 3.4

### ISSUE THREAD

**Issue by yourcelf** [jazzband/sorl-thumbnail#368]
Currently the test suite is failing on my machine for all py34-django*-pgmagick environments, because `pgmagick._pgmagick.get_blob_data` raises a `UnicodeDecodeError`.

I notice that the [import for `get_blob_data`](https://github.com/mariocesar/sorl-thumbnail/blob/5568c79fe29d011a876ef6e7453794079dc4f0aa/sorl/thumbnail/engines/pgmagick_engine.py#L7-L13) conditionally uses b64decode to import blob data instead, and it doesn't have this problem (swapping in the b64decode implementation works fine on all environments). 

Is pgmagick's implementation of `get_blob_data` used where available for performance reasons?  If so, and if it's worth it to keep that optimization, it may be necessary to also condition the implementation to use on the python version so that python>3 can be happy with the bytes returned by it.

**Comment by camilonova** [comment]
I guess we should work on python 3.5 and beyond.
