### ISSUE TITLE
Latest commit breaks migrations on Django 1.6

### ISSUE THREAD

**Issue by AndresOsinski** [jazzband/sorl-thumbnail#381]
I just saw there  a commit that's just been made for migrations in 1.8. Unfortunately, it's causing trouble with migrations in 1.6 using South.

**Comment by mariocesar** [comment]
We're not release that as an official version,  didn't plan yet to have it working with south, any ideas?

**Comment by AndresOsinski** [comment]
The Django docs for 1.8 have the following:

"To aid in this, South 1.0 will automatically look for South-format migrations in a south_migrations directory first, before looking in migrations, meaning that users’ projects will transparently use the correct set as long as you put your South migrations in the south_migrations directory and your Django migrations in the migrations directory.

More information is available in the South 1.0 release notes."

**Comment by timgraham** [comment]
I think the next version of sorl-thumbnail doesn't need to support Django 1.6 -- it's been unsupported for a long time.
