### ISSUE TITLE
Release 12.3 Changelog?

### ISSUE THREAD

**Issue by dmr** [jazzband/sorl-thumbnail#387]
Hi sorl-thumbnail Team,
I was hoping to find some information in the docs but
http://sorl-thumbnail.readthedocs.org/en/latest/news.html
looks pretty outdated.
Also the github releases don't really tell my what changed since the last version.
Where can I find information about new features in this release?

I'm a heavy user and big fan of the project, thanks for developing this!

**Comment by mariocesar** [comment]
That will be a manual work, the project don't have any automation on making the Changelog up to date. So, to fix this issue: someone (me probably if there is no volunteer) will need to read all changesets, link with the issues and redact a list of changes. Surely will be a fun task for a weekend :(

On the case, we need a determinate process to update the changelog, I'm already researching the matter, any ideas will be welcome

**Comment by dmr** [comment]
Usually I do a manual `git log --oneline --decorate --color` and then manually sort what happened.
http://stackoverflow.com/questions/3523534/good-ways-to-manage-a-changelog-using-git

I have no better tricks for you, I'm sorry. I was just confused by outdated information. To keep the process maybe remove the page from the docs and link to a file in the root folder of the repo?
Thanks.
