### ISSUE TITLE
12.3 and 12.2 Table creation broken 

### ISSUE THREAD

**Issue by n3storm** [jazzband/sorl-thumbnail#401]
Successfully installed sorl-thumbnail-12.3

django.db.utils.InternalError: (1071, u'Specified key was too long; max key length is 767 bytes')

**Comment by SalahAdDin** [comment]
:+1:

**Comment by n3storm** [comment]
Trying this: http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/

Not being lucky plus looks like a really ugly hack having to change server setup.

**Comment by n3storm** [comment]
Setting a value of  ```max_length=191 ``` or lower at ```models.py``` or migrations solves this issue, but I don't think this is "the solution" so I will not make a PR 

Any idea?

**Comment by n3storm** [comment]
Buuuuhh!!!! This error was caused because initial database creation was setup for ´´´utf8mb4_general_ci´´´ This is something that has already struck me a year ago and then again.
Better always always always: ```utf8_general_ci```

@SalahAdDin can you confirm your database is mysql and you have set database collation as ´´´utf8mb4_general_ci´´´? 

I don't know if this is a django error.

Anyway, I think this issue can be closed.
