### ISSUE TITLE
Adding Django migrations will break migrations for people still using South

### ISSUE THREAD

**Issue by andybak** [jazzband/sorl-thumbnail#404]
South < 1.0 will try and use the Django migrations in the migrations dir.

South >= 1.0 will try south_migrations directory first and fall back to the migrations dir.

In both cases this will throw an ImportError ('Can't import django.db.migrations')

Off the top of my head - the best solution is probably to add a south_migrations directory (probably can be empty apart from **init**.py) and to document the fact that South >=1.0 is required. (I don't think it's advisable to put this in requirements.txt or setup.py as users should really be made aware of this instead of just upgrading it for them)

**Comment by dsteinberger** [comment]
:+1:  With the package south_migrations it's work like a charm :)

**Comment by timgraham** [comment]
I think the next version of sorl-thumbnail doesn't need to support Django 1.6 -- it's been unsupported for a long time.
