### ISSUE TITLE
Migrating from legacy to container-based infrastructure in Travis CI

### ISSUE THREAD

**Issue by haakenlid** [jazzband/sorl-thumbnail#410]
According to Travis using container-based infrastructure should be faster. 
But that means some changes in the build process. 

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

I'm making a pull request to test it out.

**Comment by camilonova** [comment]
Thank you.
