### ISSUE TITLE
convert_engine is broken in 12.4a1

### ISSUE THREAD

**Issue by milkomeda** [jazzband/sorl-thumbnail#419]
See https://github.com/django/django/blob/master/django/core/files/temp.py#L28

```
Note that unlike tempfile.NamedTemporaryFile from the standard library,
__init__() does not support the 'delete' keyword argument in
Python 2.6+, or the 'delete', 'buffering', 'encoding', or 'newline'
keyword arguments in Python 3.0+.
```

Your code uses the delete argument on line 71 see https://github.com/mariocesar/sorl-thumbnail/blob/3541db7f4160a126eecd8441348390955e5b7779/sorl/thumbnail/engines/convert_engine.py#L71.

Will break code with `__init__() got an unexpected keyword argument 'delete'`.

Relates https://github.com/mariocesar/sorl-thumbnail/pull/392 and https://github.com/mariocesar/sorl-thumbnail/pull/358.

Why did tests pass?

**Comment by camilonova** [comment]
This issue should be outdated by now. I'm closing it.
