### ISSUE TITLE
How to pass google pagespeed

### ISSUE THREAD

**Issue by sowinski** [jazzband/sorl-thumbnail#447]
Hey guys,

I am wondering if there is a way with sorl-thumbnail to pass google pagespeed? 
Easy-thumbnail supports post-processors to optimize a jpeg with jpegtran oder jpegoptim. Is there something similar in sorl-thumbnail?

If not, do you have a good idea how I can solve this problem?

Thank you!

**Comment by truhlik** [comment]
@sowinski: Did you solve the issue with Google somehow?

Thank you

**Comment by john-parton** [comment]
Here's a hack:

```python
import subprocess

from sorl.thumbnail.engines.pil_engine import Engine as BaseEngine


class Engine(BaseEngine):

    def _get_raw_data(self, image, format_, quality, image_info=None, progressive=False):

        if format_ != 'JPEG':
            return super()._get_raw_data(image, format_, quality, image_info=image_info, progressive=progressive)

        raw_data = super()._get_raw_data(image, 'BMP', quality, image_info=image_info, progressive=progressive)

        mozjpeg = subprocess.run(
            ['mozjpeg', '-quality', str(quality)], input=raw_data, stdout=subprocess.PIPE, check=True
        )

        return mozjpeg.stdout
```

You'll need to update the `THUMBNAIL_ENGINE` setting to point to the new class.

Works with Python 3.5.  You have to have the mozjpeg binary somewhere on your path.

**Comment by Flimm** [comment]
Thanks, @john-parton , I think this will be a helpful answer to anyone else looking for help on how to use `mozjpeg` in `sorl-thumbnail`.

@sowinski , does this answer your question?

**Comment by sowinski** [comment]
@john-parton Thank you :) 

@Flimm Yes!
