### ISSUE TITLE
image orientation problem with Pillow > 3.0

### ISSUE THREAD

**Issue by ggilley** [jazzband/sorl-thumbnail#454]
I'm getting cropped thumbnails when using Pillow with an image orientation of 6 (90 degrees CCW rotation). It looks like Pillow changed the rotate call in 3.0 to require an additional option of you want to change the image buffer on rotation. (see https://github.com/python-pillow/Pillow/issues/1500). The fix would be to add the expand=1 option to the pil_engine.py file with 90 degree rotations. I attached a file that will render incorrectly with Pillow=3.2

![20160612151812](https://cloud.githubusercontent.com/assets/3057017/15992655/e2bc00a4-3085-11e6-8ac1-bf39ae72ee04.jpg)

And here's the incorrect result:
![be1d685c71f5f16afd8db306abb54892](https://cloud.githubusercontent.com/assets/3057017/15992662/21c4c9ac-3086-11e6-96af-9d4c79c96b28.jpg)

**Comment by ataylor32** [comment]
#455 fixes this

**Comment by dtougas** [comment]
I am currently using Pillow 4.1.1 and sorl-thumbnail 12.4a1, and am seeing this problem. Should I be using a different version of either of those packages?
