### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by nuschk** [jazzband/sorl-thumbnail#466]
I'm with django 1.9 and planning to go 1.10. AFAIK, the latest stable release (12.3) does not support django 1.9. Should I just be using 12.4a then? And, when will you release 12.4, are there any obstacles?

**Comment by vesterbaek** [comment]
@mariocesar The latest release is an alpha and more than one year old. What is the current state of master - and are there any plans of cutting a new release anytime soon?

**Comment by mariocesar** [comment]
@vesterbaek the main issue is backward compatibility.

I agree is had been a long wait, now that django drop supports for olders versions, I will like to review drop some fixes, specifically the TEMPLATE_DEBUG, and possible others

**Comment by vesterbaek** [comment]
@mariocesar ok, thanks. Not be be pushy, but do you have any timeline in your head regarding when a new version should hit pypi? Is HEAD of master generally considered safe to use?

**Comment by someidiot** [comment]
I just spent days tracking down and fixing a bug only to find that it has already been solved here ([316](https://github.com/mariocesar/sorl-thumbnail/issues/316)), but not yet pushed to pypi :( Please update soon!

**Comment by SalahAdDin** [comment]
@mariocesar soon!

**Comment by Flimm** [comment]
`sorl-thumbnail` is now a [Jazzband](https://jazzband.co/) project. As soon as we can get the tests to pass, I think any member of Jazzband can release the next version on PyPI.

**Comment by camilonova** [comment]
Use the latest one https://pypi.python.org/pypi/sorl-thumbnail/12.4.1
