### ISSUE TITLE
Improvement: Redis Sentinel HA Support and Dockerized Travis CI 

### ISSUE THREAD

**Issue by danigosa** [jazzband/sorl-thumbnail#468]
I have introduced Redis Sentinel Cluster support and (due to the lack of Sentinel service in Travis) I added dockerized tests with Docker Compose instead of pure travis, all changes are here, tell me if you interested in a PR:

https://github.com/danigosa/sorl-thumbnail/commit/d151d40665be5542e03f55bc730f73862fb72119

**Comment by camilonova** [comment]
Not really. Thanks.
