### ISSUE TITLE
Deprecated `TEMPLATE_DEBUG` setting is required by sorl-thumbnail

### ISSUE THREAD

**Issue by philgyford** [jazzband/sorl-thumbnail#476]
The `TEMPLATE_DEBUG` setting which was deprecated in Django 1.8 and 1.9, and is missing from [1.10's docs](https://docs.djangoproject.com/en/1.10/ref/settings/#template-debug) (so I assume it's now obsolete) is required by sorl-thumbnail.

Without a `TEMPLATE_DEBUG` setting I get this when I try and use the `{% thumbnail ... %}` tag in a template:

`'Settings' object has no attribute 'TEMPLATE_DEBUG'`

If I add it to my settings, the template tag works.

**Comment by dimitry** [comment]
Try installing directly from Github (add to requirements.txt):
`-e git+https://github.com/mariocesar/sorl-thumbnail.git#egg=sorl-thumbnail`

Looks like latest version on pip is 12.4a1 and doesn't reflect Django 1.10 changes.

**Comment by bfincher** [comment]
Are there any plans on getting a new version uploaded to pip?

**Comment by Flimm** [comment]
I would also appreciate a new version on Pypi.

**Comment by idrummer83** [comment]
I have the same trouble

**Comment by PetrDlouhy** [comment]
@mariocesar Could you please update the PyPI package?

**Comment by mariocesar** [comment]
Tests are not passing for te master branch, it needs first to pass and take care of that. 

Hope to have the time soon , however anyone is welcome to give it look and commit

**Comment by pixelead0** [comment]
Please update the PyPi package.

**Comment by SalahAdDin** [comment]
Please update it.

**Comment by Flimm** [comment]
sorl-thumbnail is now part of Jazz Band, anyone can join and contribute fixes, and a new version on PyPI should be released automatically if the tests pass.

**Comment by adi-** [comment]
WHy this is closed?! Issue is not fixed

**Comment by Flimm** [comment]
@adi- This issue is not closed. As you can see at the top of the page, this issue is still open.

**Comment by adi-** [comment]
Damn, I have looked at the status two comments above. Sorry.

**Comment by olymk2** [comment]
just hit this myself, with latest django any chance of an updated package any time soon on pip ?

**Comment by Flimm** [comment]
@olymk2 A new version on PyPI is waiting on @jazzband/roadies or @mariocesar, as they are the only ones who have access to the [PyPI package](https://pypi.python.org/pypi/sorl-thumbnail). See #507 and https://github.com/jazzband/roadies/issues/69 .

**Comment by delitamakanda** [comment]
I actually have an issue with this package on heroku. 
it doesnt migrate with `heroku run python3 manage.py migrate` and the table is not create ? Any ideas ? Thank you

**Comment by Q-back** [comment]
@dimitry your method doesn't work for me :( Django 1.11

**Comment by camilonova** [comment]
Just released. https://pypi.python.org/pypi/sorl-thumbnail/12.4.1
