### ISSUE TITLE
Add `sorl_thumbnail_tags` templatetag library that mirrors traditional `thumbnail`

### ISSUE THREAD

**Issue by barseghyanartur** [jazzband/sorl-thumbnail#480]
Add `sorl_thumbnail_tags` templatetag library that mirrors traditional `thumbnail`.

This allows usage of sorl-thumbnail in templates by {% load sorl_thumbnail_tags %} instead of traditional {% load thumbnail %}. It's specifically useful in projects that do make use of multiple thumbnailer libraries (for instance `easy-thumbnails` alongside `sorl-thumbnail`).

Works fine in my [fork](https://github.com/barseghyanartur/sorl-thumbnail/blob/master/sorl/thumbnail/templatetags/sorl_thumbnail_tags.py). If you, in principle, have nothing against addition of `sorl_thumbnail_tags` mirror, I'll add tests and update the documentation prior making a pull request.

**Comment by sephii** [comment]
I think that's a good idea. Having a name as generic as `thumbnail` is too likely to conflict with other thumbnail libraries like easy-thumbnails.

**Comment by barseghyanartur** [comment]
@mariocesar:

Are you interested in fix from my side (and thus a pull-request) or rather do it yourself?

**Comment by barseghyanartur** [comment]
Since it's moved to JazzBand, I ask again, is there anyone interested in fix from my side (and thus a pull-request) or rather do it yourself?

**Comment by SalahAdDin** [comment]
@barseghyanartur Make a PR.
