### ISSUE TITLE
tox.ini file missing?

### ISSUE THREAD

**Issue by JordanReiter** [jazzband/sorl-thumbnail#487]
According to README, testing is done via tox. However, there does not appear to be a tox.ini file present.

**Comment by timgraham** [comment]
It was removed in a147388c9ed7aa0ca43550a3ecaf6d1a97ac6a82, I'm not sure how things are supposed to be working. Travis seems to be running okay, though all builds have failures.

**Comment by Flimm** [comment]
It seems that Tox reads from `setup.cfg`, but only sometimes, it's an experimental feature: https://github.com/tox-dev/tox/issues/545

**Comment by obestwalter** [comment]
@flimm - if you want to configure tox in setup.cfg it looks like you can after all, but you have to prefix **all** sections with 'tox'. Therefore: `[tox:tox]` for the global settings

**Comment by Flimm** [comment]
Similar issue which was created recently: https://github.com/jazzband/sorl-thumbnail/issues/525
