### ISSUE TITLE
Support Django 1.11 and Python 3.6

### ISSUE THREAD

**Issue by Flimm** [jazzband/sorl-thumbnail#491]
Django 1.11 has been released, which is the first version of Django that supports Python 3.6. It would be nice if sorl-thumbnail supported these versions.

**Comment by istinspring** [comment]
Yes, looks like AdminImageMixin does not work with django 1.10

**Comment by hobarrera** [comment]
Thumbnailing itself works fine for me since I've some apps that've been using this for weeks. I can't confirm about the admin mixin.

**Comment by hobarrera** [comment]
Python 3.6 has never been an issue, since I've been using that everywhere since release.

**Comment by MartinBorg** [comment]
At least one unittest seems to have a problem with Django 1.11:
https://bugs.debian.org/865891

**Comment by Flimm** [comment]
Tests pass now in Python 3.6 and Django 1.11. Let's close this once there is a release on PyPI.

**Comment by GitRon** [comment]
@Flimm Any ideas/plans when the release to PyPI will happen? Thx!

**Comment by Flimm** [comment]
@GitRon That's outside of my control. See #507.

**Comment by GitRon** [comment]
@Flimm Thx for the link

**Comment by camilonova** [comment]
Here it is https://pypi.python.org/pypi/sorl-thumbnail/12.4.1
