### ISSUE TITLE
Feature request: crop=contain

### ISSUE THREAD

**Issue by Flimm** [jazzband/sorl-thumbnail#496]
It would be great if the template tag `{% thumbnail %}` could take an option similar to CSS's option `background-size: contain`.

For instance, it would be nice to be able to fit a square reddish image (60x60) into the destination image size (120x60) so that it would look like this:

![contain](https://cloud.githubusercontent.com/assets/355454/25893042/4b85d54a-356e-11e7-8a36-f25f12612c0e.png)

This would be useful for generating images for OpenGraph, for instance.

**Comment by haakenlid** [comment]
Is this different from the existing `padding` options? https://sorl-thumbnail.readthedocs.io/en/latest/template.html#padding

**Comment by Flimm** [comment]
@haakenlid Thank you, that's exactly what I wanted.

The code is:

```
{% thumbnail foobar "120x60" padding=True padding_color="#000000" as im %}
<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% endthumbnail %}
```
