### ISSUE TITLE
"news" in docs are outdated ;)

### ISSUE THREAD

**Issue by jedie** [jazzband/sorl-thumbnail#498]
http://sorl-thumbnail.readthedocs.io/en/latest/news.html is outdated:

![grafik](https://cloud.githubusercontent.com/assets/71315/26553845/b82b22c6-448d-11e7-9bc7-7b2321c1c1cd.png)

**Comment by Flimm** [comment]
I've updated `news.rst`, please close once ReadTheDocs updates the website. f7bc4d00d50a7d15139414b7a7dd27266fc0e62e

**Comment by camilonova** [comment]
I removed the file. Changes file should provide what you need.
