### ISSUE TITLE
Pillow 3.7 doesn't support RGBA as JPEG mode

### ISSUE THREAD

**Issue by Darou** [jazzband/sorl-thumbnail#503]
Hi!

Before Pillow 3.7 the code at PIL/JpegImagePlugin.py had a deprecation warning about using RGBA on a JPEG image and converted it to RGB.

```
if im.mode == 'RGBA':
    warnings.warn(
        'You are saving RGBA image as JPEG. The alpha channel will be '
        'discarded. This conversion is deprecated and will be disabled '
        'in Pillow 3.7. Please, convert the image to RGB explicitly.',
        DeprecationWarning
    )
```
As the comment says it has been deprecated since 3.7.

A way to solve it would be to modify pil_engine.py, overwritting colorspace (the wrapper) to forward the image format to _colorspace, and then converting it to RGB if it's a JPEG with RGBA

**Comment by konradko** [comment]
A workaround until this is gonna be fixed: change the default thumbnail format to PNG: http://sorl-thumbnail.readthedocs.io/en/latest/reference/settings.html#thumbnail-format
