### ISSUE TITLE
sorl-thumbnail on ReadTheDocs is not up-to-date

### ISSUE THREAD

**Issue by Flimm** [jazzband/sorl-thumbnail#505]
Have a look at this link: https://sorl-thumbnail.readthedocs.io/en/latest/news.html

This does not contain the latest content of https://github.com/jazzband/sorl-thumbnail/blob/master/docs/news.rst

Perhaps sorl-thumbnail.readthedocs.io needs to be migrated to jazzband/sorl-thumbnail somehow?

**Comment by camilonova** [comment]
It was just fixed. Thanks.

**Comment by Flimm** [comment]
Thanks. 

Interestingly, this link works: http://sorl-thumbnail.readthedocs.io/en/12.4.1/news.html

But this link doesn't: https://sorl-thumbnail.readthedocs.io/en/latest/news.html
