### ISSUE TITLE
sorl thumbnail not working: thumbnail not created

### ISSUE THREAD

**Issue by Six-wars** [jazzband/sorl-thumbnail#509]
Having an issue with sorl-thumbnail, it's working (not crashing) but fails to create a thumbnail. I've done a migration and it used to work, I just noticed it's no longer working.

Here's some code to better explain the issue, I'm running it from the django shell

	In [1]: from sorl.thumbnail import get_thumbnail

	In [2]: from PIL import Image as PILImage

	In [3]: image = PILImage.open('revamp/media/27fd720f410e8cd57600b409b7cbea15.jpg')

	In [4]: im = get_thumbnail(image, '{0}x{1}'.format(450, 500), quality=100)

	In [5]: im.url
	Out[5]: '/media/cache/33/71/33711b06366a689da7ba758d8a08cd17.jpg'

	[7:37] 
	samuel@samuel-pc:~/Documents/code/revamp/revamp/media$ cd cache/33
	samuel@samuel-pc:~/Documents/code/revamp/revamp/media/cache/33$ cd 71
	bash: cd: 71: No such file or directory

**Comment by Christophe31** [comment]
is it a duplicate ? #565
