### ISSUE TITLE
(Cached) thumbnail rendering too slow (1s per thumbnail)

### ISSUE THREAD

**Issue by salvacarrion** [jazzband/sorl-thumbnail#510]
I'm working with the latest version of sorl-thumbnail (12.4a1) in a distributed system and the rendering is way too slow, around 1s/thumbnail.

##### Software used
- sorl-thumbnail 12.4a1
- Python 3.5
- Django 1.11.3
- Google Cloud Storage
- Redis 4.0 (through a Unix socket)
- Ubuntu 17.04 (GNU/Linux 4.10.0-32-generic x86_64).

##### Expected behavior
The thumbnail rendering should be practically instantaneous if cached.

##### Actual behavior
The thumbnail rendering when cached takes around 1 second _(0.5-1.5s)_.

##### Steps to reproduce the behavior

```
{% thumbnail user.image.image as img %}
     <img src="{{ img.url }}">
{% empty %}
     <img src="{% static 'public/images/default.svg' %}">
{% endthumbnail %}
```

##### Additional info

I've identified a few problems:

**1) Line 153: `output = self.nodelist_file.render(context)` takes ~1 second to render**

```
Timer unit: 1e-06 s

Total time: 0.604442 s
File: /Users/[...]/lib/python3.6/site-packages/sorl/thumbnail/templatetags/thumbnail.py
Function: _render at line 129

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   129                                               @profile_each_line
   130                                               def _render(self, context):
   131         1           53     53.0      0.0          file_ = self.file_.resolve(context)
   132         1            6      6.0      0.0          geometry = self.geometry.resolve(context)
   133         1            0      0.0      0.0          options = {}
   134         3            3      1.0      0.0          for key, expr in self.options:
   135         2            2      1.0      0.0              noresolve = {'True': True, 'False': False, 'None': None}
   136         2           13      6.5      0.0              value = noresolve.get(text_type(expr), expr.resolve(context))
   137         2            2      1.0      0.0              if key == 'options':
   138                                                           options.update(value)
   139                                                       else:
   140         2            2      1.0      0.0                  options[key] = value
   141                                           
   142         1         1832   1832.0      0.3          thumbnail = get_thumbnail(file_, geometry, **options)
   143                                           
   144         1            2      2.0      0.0          if not thumbnail or (isinstance(thumbnail, DummyImageFile) and self.nodelist_empty):
   145                                                       if self.nodelist_empty:
   146                                                           return self.nodelist_empty.render(context)
   147                                                       else:
   148                                                           return ''
   149                                           
   150         1            2      2.0      0.0          if self.as_var:
   151         1            9      9.0      0.0              context.push()
   152         1            3      3.0      0.0              context[self.as_var] = thumbnail
   153         1       602506 602506.0     99.7              output = self.nodelist_file.render(context)
   154         1            6      6.0      0.0              context.pop()
   155                                                   else:
   156                                                       output = thumbnail.url
   157                                           
   158         1            1      1.0      0.0          return output
```

**2) The class `ImageFile(BaseImageFile)` from sorl.thumbnail.images takes between 0.5-1 second if used with Google Cloud Storage from _django-storages_ due to the methods of `self.storage`**

This lag is especially noticeable in this section of the previously mentioned class:

```
 if hasattr(self.storage, 'location'):
            location = self.storage.location
            if not self.storage.location.endswith("/"):
                location += "/"
            if self.name.startswith(location):
                self.name = self.name[len(location):]
```

##### HINT:
I think many of the performance problems could be related to the function `url` of ImageFile(BaseImageFile) because the APIs of cloud storages can be a bit tricky.

```
Timer unit: 1e-06 s

Total time: 0.832383 s
File: /Users/[...]/lib/python3.6/site-packages/sorl/thumbnail/images.py
Function: url at line 159

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   159                                               @property
   160                                               @profile_each_line
   161                                               def url(self):
   162         1       832383 832383.0    100.0          return self.storage.url(self.name)
```

**Comment by salvacarrion** [comment]
A simple solution to work around this problem is to modify the `url` function of `ImageFile` so that it composes the _MEDIA URL_ using the standard storage (or a simple function such as `urljoin(base_url, url)`) instead of the DFS API. 

The reason behind this is to overcome the lag _(0.5-1.5s)_ introduced by the DFS API (here _django-storages_ -> _Apache LibCloud - Google Cloud_) when asking for URL directly to the DFS.


In _sorl/thumbnail/images.py:_

```
from django.core.files.storage import FileSystemStorage


class ImageFile(BaseImageFile):
     [...]

     def __init__(self, file_, storage=None):
          # Add this line
          self.standard_storage = FileSystemStorage()

     [...]

     @property
         def url(self):
             if settings.THUMBNAIL_FAST_URL:
                 return self.standard_storage.url(self.name)
             else:
                 return self.storage.url(self.name)
```

`THUMBNAIL_FAST_URL` is a boolean variable set in _settings.py_ to enable this function.

**Comment by jdmueller** [comment]
I am not sure if my problem is the same as what you have documented. I am going to try your suggestion and see if it fixes my issue. I am dealing with something that sounds like the same issue. I have a production site that is running using gunicorn/nginx and does not use django-storages since it is running from the filesystem. Recently I have containerized my project into a docker container using django-storages and uWSGI running on AWS. That seems to be the only difference. The site on my old host that is running without storages runs everything very very fast. The page I am comparing loads in a matter of 1-3 seconds, VS the containerized version with storages/uWSGI takes 15+ seconds to load. I have spent a couple of days now trying different configurations and ultimately I am very disappointed since the new host is setup on AWS with great specs and a dedicated DB using RDS and the Elasticache service. I was expecting this to run better. I will try your code update and see if this resolves my issue.

**Comment by jdmueller** [comment]
Thank you so much for your genius answer. Solved my problem!!!

To make this easier for anyone else I created a package for pip with these mods:
https://pypi.org/project/sorl-thumbnail-jdmueller/

And just add these to settings.py:
MEDIA_URL = "https://" + os.environ.get("AWS_STORAGE_BUCKET_NAME", "bucket-name") + ".s3.amazonaws.com/"
THUMBNAIL_FAST_URL = True

**Comment by rettier** [comment]
The problem still exists. On deserialization from the cache the storage class is constructed again for each thumbnail when the url is resolved. As the storage class is constructed from it's name (e.g. `utils.TumbnailStorage`) pointing `THUMBNAIL_STORAGE` to a function which returns a singleton instance (e.g. `utils.get_thumbnail_storage`) does not solve the issue as the full class name is later saved to cache and _not_ the original value of `THUMBNAIL_STORAGE`).

My solution, albeit somewhat ugly, is to return a class which proxies its attributes to a global instance:

**utils.py:**
```python
class SingletonThumbnailStorage:
    _storage = None

    def __init__(self, **settings):
        if not SingletonThumbnailStorage._storage:
            SingletonThumbnailStorage._storage = ThumbnailStorage(**settings)

    def __getattr__(self, item):
        return getattr(SingletonThumbnailStorage._storage, item)

    def __call__(self, *args, **kwargs):
        return SingletonThumbnailStorage._storage(*args, **kwargs)


class ThumbnailStorage(GoogleCloudStorage):
    def __init__(self, **config):
        config["location"] = "thumbnails"
        config["querystring_auth"] = False
        super().__init__(**config)
```

**settings.py**
```python
THUMBNAIL_STORAGE = "utils.SingletonThumbnailStorage"
```

**Comment by kciredor** [comment]
I'm hitting this issue as well, with redis and google storage backend.
