### ISSUE TITLE
Use Sorl Thumbnail with Django Rest Framework

### ISSUE THREAD

**Issue by feedgit** [jazzband/sorl-thumbnail#517]
How can I use sorl thumbnail with DRF? I follow instruction Low API: http://sorl-thumbnail.readthedocs.io/en/latest/examples.html#low-level-api-examples and get error: my_file is not defined in model. Please help me.

**Comment by mark-mishyn** [comment]
`if obj.photo:
    return get_thumbnail(obj.photo, '30x30', crop='center', quality=99).url`

and photo is ImageField

**Comment by feedgit** [comment]
Thank you. Hope Sorl Thumbnail support for DRF in the future :)

**Comment by SalahAdDin** [comment]
Can you put it in the documentation?

**Comment by kidig** [comment]
FYI, I've found useful package for DRF: https://github.com/dessibelle/sorl-thumbnail-serializer-field

**Comment by SalahAdDin** [comment]
@kidig Can you put it at documentation?

**Comment by Atorich** [comment]
@maxim25 
https://github.com/dessibelle/sorl-thumbnail-serializer-field/blob/master/sorl_thumbnail_serializer/fields.py
There is the whole codebase. Nothing about any extra database queries. Please, check your querysets.
