### ISSUE TITLE
Removal of query args break functionality

### ISSUE THREAD

**Issue by schyffel** [jazzband/sorl-thumbnail#542]
I have a problem with how sorl-thumbnail removes query args from URL:s.

images.py:
```
        # Remove query args from names. Fixes cache and signature arguments
        # from third party services, like Amazon S3 and signature args.
        self.name = self.name.split('?')[0]
```

This might be great for S3-servers, but really bad for others. One example is a site that adds **?format=jpg** to image urls, and returns a 404 if you remove that. That will not work with this code.

It would be great if this could be made an option in sorl-thumbnail, possibly with the option to add a list of patterns for servers where args should be removed.

**Comment by schyffel** [comment]
I added a pull request to solve this with a setting.

**Comment by timgraham** [comment]
PR is https://github.com/jazzband/sorl-thumbnail/pull/543.
