### ISSUE TITLE
please release the latest version to PyPI

### ISSUE THREAD

**Issue by mtb-beta** [jazzband/sorl-thumbnail#546]
The PR of #530 has been merged into the master branch, but it has not been released to PyPI. 

Could you release version that imported #530 to PyPI ?

Thank you.

**Comment by timgraham** [comment]
@camilonova - are you a lead for this project who can do a release? If needed, I can help with tasks like putting release notes together.

**Comment by matthiask** [comment]
Maybe pushing a tag is sufficient for releasing? `.travis.yml` contains a deploy: section.

**Comment by camilonova** [comment]
@timgraham sure man, go on and let me know.

**Comment by camilonova** [comment]
Fixed in #563

**Comment by Flimm** [comment]
@camilonova The latest version on PyPI is still 12.4.1, released back in Nov 2017, so it looks like a newer version has not been released. If you were expected Travis CI to handle the release, it looks like the build failed: https://travis-ci.org/jazzband/sorl-thumbnail/jobs/428373120

**Comment by timgraham** [comment]
It's merged now.

**Comment by Flimm** [comment]
Thank you @timgraham , @camilonova and everyone one who contributed to this release 12.5.0 . It's appreciated.
