### ISSUE TITLE
[BUG] : 'ascii' codec can't encode character '\xe9' in position 56: ordinal not in range(128)

### ISSUE THREAD

**Issue by hugodes** [jazzband/sorl-thumbnail#566]
When trying to upload an image in Safari (12.0) using 

```
from sorl.thumbnail import ImageField

image = ImageField('image', upload_to='images', null=True)

```
If the path of the file contains an accent (é, è etc.) than the server throws the following error:

> 'ascii' codec can't encode character '\xe9' in position 56: ordinal not in range(128)

**Comment by hugodes** [comment]
This happens in Chrome and FF also.

**Comment by claudep** [comment]
This is not related directly to sorl.thumbnail. You should run Python/Django with an UTF-8 locale, and this error should disappear.
