### ISSUE TITLE
Error low level API with `HTTPS` url

### ISSUE THREAD

**Issue by millerf** [jazzband/sorl-thumbnail#594]
I am using `sorl` to generate thumbnails in my project. everything works fine except when using https URLS.

```
 geometry_string = request.query_params.get('geometry_string', 'x100')
 crop = request.query_params.get('crop', 'center')
 quality = int(request.query_params.get('quality', '99'))
 _format = request.query_params.get('img_format', 'JPEG')
 im = sorl_get_thumbnail(im_file, geometry_string=geometry_string, crop=crop, quality=quality, format=_format)
```

Works fine with `im_file` being `http://8images.cgames.de/images/gamestar/4/tests-kanal-icon_6023667.jpg`, 
but crashes with `https://8images.cgames.de/images/gamestar/4/tests-kanal-icon_6023667.jpg` (note the http*s*)

Anyone with an idea? Using it on MAC/Ubuntu with Pillow 5.4.1

**Comment by claudep** [comment]
I guess that there was some certificate issue. If anyone can still reproduce this, please reopen with a full traceback.
