### ISSUE TITLE
Exceptions when users upload a GIF

### ISSUE THREAD

**Issue by uri-rodberg** [jazzband/sorl-thumbnail#599]
Hi,

We are using `sorl-thumbnail==12.5.0` in [Speedy Net](https://github.com/speedy-net/speedy-net). I found out that an exception is raised when users upload an animated GIF to the server. The exception is raised when viewing the user's profile, which uses `sorl-thumbnail` to try to create a thumbnail. I submitted an [issue](https://github.com/python-pillow/Pillow/issues/4235) on `python-pillow/Pillow` but I understand now the bug might be in `sorl-thumbnail`. I received an exception - `OSError` - `cannot write mode RGBA as JPEG` - in `env/lib/python3.6/site-packages/PIL/JpegImagePlugin.py in _save, line 621`. Is there a way to fix this bug?

The errors come from `env/lib/python3.6/site-packages/sorl/thumbnail/templatetags/thumbnail.py` when using the `thumbnail` template tag.

Another problem is that some images (see example below) display a thumbnail in some circumstances, but the thumbnail is empty in some circumstances (maybe depending on size) and therefore there is no thumbnail for a user who uploaded these images in some pages on Speedy Net, and he appears as a user who didn't upload a profile picture at all.

Thanks,
אורי.

**Comment by uri-rodberg** [comment]
Hi,

I added a validator called [`validate_photo_for_user`](https://github.com/speedy-net/speedy-net/commit/b1ee35b41b82c12f5983d30ce0aa843e0af78ccf#diff-53f67b16827497bcf5311316b73f1d13R48) to catch this exception, and don't accept the file if there is an exception (any exception) when creating a thumbnail. But, if there is an exception in the user's profile view, the server will still fail. I hope you can fix this error so that exceptions will not be raised when creating a thumbnail.

**Comment by uri-rodberg** [comment]
An example of an animated GIF who causes an exception:

![gif-shaking-back-forth](https://user-images.githubusercontent.com/12808124/69911426-101dfb80-1424-11ea-92f0-f84e1cde7060.gif)

This GIF doesn't cause an exception, but the thumbnail is empty in some circumstances (maybe depending on size) and therefore there is no thumbnail for a user who uploaded this GIF in some pages on Speedy Net:
![earth](https://user-images.githubusercontent.com/12808124/69911435-2330cb80-1424-11ea-8a8c-eab289ff006e.gif)

**Comment by uri-rodberg** [comment]
Setting THUMBNAIL_FORMAT to PNG solves this problem.

I'm closing this issue for now.

**Comment by anka-sirota** [comment]
> Setting THUMBNAIL_FORMAT to PNG solves this problem.

Changing default thumbnailing options does not seem like a good solution IRL.

Could we just fix this issue, making transparent GIFs work with default format settings instead? https://github.com/jazzband/sorl-thumbnail/pull/653
