### ISSUE TITLE
Support Django 3.0

### ISSUE THREAD

**Issue by uri-rodberg** [jazzband/sorl-thumbnail#601]
This line does not work with Django 3.0:

`from django.utils.encoding import python_2_unicode_compatible`

https://docs.djangoproject.com/en/3.0/releases/3.0/

You can import directly from six if you still need to support Python 2.

**Comment by hugodes** [comment]
As far as I can see a PR has been made: #600

**Comment by uri-rodberg** [comment]
> As far as I can see a PR has been made: #600

You can close this issue after Django 3.0 is supported in the latest release.

**Comment by devova** [comment]
https://github.com/jazzband/sorl-thumbnail/pull/600 is merged but no tag/release has been made!

**Comment by moseb** [comment]
A new release would be lovely please please :smile:

**Comment by hugodes** [comment]
Pretty please @camilonova 🙏🏻

**Comment by bfincher** [comment]
You can update your requirements.txt file with the following line until a release is made:  git+git://github.com/jazzband/sorl-thumbnail@4fe1854#egg=sorl-thumbnail

**Comment by danidee10** [comment]
Just adding my voice here. Please make a release! :pray:  Thanks

**Comment by camilonova** [comment]
Someone please approve #604

**Comment by inoks** [comment]
@benjaoming Can you please approve #604?

**Comment by benjaoming** [comment]
@inoks I already approved it, that has no effect. I don't have write access to the repo as noted in #604.

**Comment by yuweichen1008** [comment]
The bug seems to unfix at Django 3.0
