### ISSUE TITLE
pip install doesn't find 12.6 release

### ISSUE THREAD

**Issue by rambasnet** [jazzband/sorl-thumbnail#606]
I'm guessing that 12.6 release provides support for Django 3. pip can't find 12.6 release yet, any thoughts?

**Comment by farin** [comment]
it wasn't published yet
You can install from branch as workaround
`pip install -e git+git://github.com/jazzband/sorl-thumbnail@12.6.0-release#egg=sorl-thumbnail`

**Comment by rambasnet** [comment]
great, thanks!

**Comment by dokterbob** [comment]
Poke! Would be great to have a publish!
Thanks!
