### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Butonix** [jazzband/sorl-thumbnail#609]
Django 3.0.2
from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

'sorl.thumbnail.templatetags.sorl_thumbnail': No module named 'django.utils.six

**Comment by studybuffalo** [comment]
This is a known issue with Django 3.0. Should be fixed in the 12.6.0 release, which appears ready to go, but awaiting upload to PyPI.

A temporary workaround is here: https://github.com/jazzband/sorl-thumbnail/issues/601#issuecomment-567195005
