### ISSUE TITLE
Serving Static Files

### ISSUE THREAD

**Issue by DarwinSurvivor** [jazzband/sorl-thumbnail#61]
I can't find any way to thumbnail a static (in STATIC_ROOT) file. It only seems to work on external (http://....) and media (in MEDIA_ROOT) files.

This is very helpful when the output size of a static image is not always the same (be it through user preferences, theming, etc)

**Comment by marcinn** [comment]
After five years still there is no possibility to generate thumbs from static files without changing the DEFAULT storage, because of https://github.com/mariocesar/sorl-thumbnail/blob/master/sorl/thumbnail/base.py#L100
StackOverflow will not help due to implementation.

Any chances to FIX that? Passing custom storage instance via `get_thumbnail()` will be enough.

**Comment by marcinn** [comment]
Here is an example of a patch https://github.com/marcinn/sorl-thumbnail/commit/61557b41169f0656063c557735ef62908a5fcaab

After applying it anyone can easily generate thumbnails for anything.
It is possible to create a custom template tag like this one:

```python
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django import template
from sorl.thumbnail.templatetags.thumbnail import ThumbnailNode


register = template.Library()
storage = FileSystemStorage(
        location='/path/to/custom/static/files',
        base_url=settings.STATIC_URL)


class StaticThumbnailNode(ThumbnailNode):
    def _get_thumbnail(self, file_, geometry, **options):
        options['storage'] = storage
        return super(StaticThumbnailNode, self)._get_thumbnail(
                file_, geometry, **options)


@register.tag
def static_thumbnail(parser, token):
    return StaticThumbnailNode(parser, token)
``` 

Please note that settings do not need to be changed.
