### ISSUE TITLE
sorl-thumbnail docs on readthedocs are outdated

### ISSUE THREAD

**Issue by lancegoyke** [jazzband/sorl-thumbnail#649]
Hey team,

I went to add in some documentation on the `THUMBNAIL_REDIS_URL` setting, but after forking the repository, saw there was [already some documentation written.](https://github.com/jazzband/sorl-thumbnail/blob/master/docs/reference/settings.rst)

It looks like the repository code hasn't been sent to readthedocs, as I cannot find info about `THUMBNAIL_REDIS_URL` on [the published documentation page.](https://sorl-thumbnail.readthedocs.io/en/latest/reference/settings.html#thumbnail-storage)

**Comment by claudep** [comment]
The sorl-thumbnail config on readthedocs.org is still pointing to the previous repository URL, hence the outdated documentation. Who is able to change that? @mariocesar? Or can the Jazzband bot do anything for that?

**Comment by camilonova** [comment]
Only @jezdez can. I'm still underage to be an admin ;)

**Comment by jezdez** [comment]
No need to be snarky @camilonova! 😜

I just fixed the settings and also set up the pull request integration, so you'll see if the docs don't successfully build.

**Comment by claudep** [comment]
Thanks @jezdez, you are our hero :trophy:
