### ISSUE TITLE
Add more leads to the project

### ISSUE THREAD

**Issue by claudep** [jazzband/sorl-thumbnail#654]
Currently only @camilonova is a project lead (https://jazzband.co/projects/sorl-thumbnail), and we can read in #589 that is not always very responsive.

It'd be great to have at least two more leads, it would be a pity that Jazzband projects are again stuck because of a lead "bus-factor".

**Comment by camilonova** [comment]
Sure go on. I agree to have more people on board.

**Comment by camilonova** [comment]
For anyone interested here is the place https://github.com/jazzband-roadies/help/issues/new?assignees=&labels=lead&template=project_lead.md&title=Project+Lead%3A+sorl-thumbnail
