### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [jazzband/sorl-thumbnail#675]
We are looking forward to using `sorl-thumbnail` with Django 3.2 on [edX](https://github.com/edx).

Required PR - #674 is already merged into the master branch.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by jramnai** [comment]
@camilonova, can you please take a look at this?

**Comment by natabene** [comment]
@camilonova Could you please have a look at this PR? We at the Open edX Team would highly appreciate a new release.

**Comment by natabene** [comment]
@camilonova Just checking to see if there have been any news.

**Comment by camilonova** [comment]
Not yet https://github.com/orgs/jazzband/teams/sorl-thumbnail/discussions/1

**Comment by natabene** [comment]
Thanks for an update! @camilonova

**Comment by jayvdb** [comment]
Django 4 is out, so we should try to support it.
https://github.com/jazzband/sorl-thumbnail/issues/680

**Comment by jayvdb** [comment]
Also CI doesnt include Python 3.9 or 3.10

**Comment by jayvdb** [comment]
And https://github.com/jazzband/sorl-thumbnail/issues/681 means the repo is currently borked for testing.  Probably the same problem @kckaiwei saw at https://github.com/jazzband/sorl-thumbnail/pull/552#issuecomment-950216882

**Comment by jayvdb** [comment]
I think we have no more blockers for a release.

**Comment by camilonova** [comment]
@jezdez can you please take a look?

**Comment by claudep** [comment]
Changelog PR: #685.
