### ISSUE TITLE
Officially support Django 3.1, 3.2, 4.0 and Python 3.9, 3.10 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [jazzband/sorl-thumbnail#683]
PyPi only lists support of `sorl-thumbnail` to Django <= 3.0 and Python <= 3.8. I would like to see `sorl-thumbnail` officially supporting newer versions - Django 3.1, 3.2, 4.0 and Python 3.9, 3.10. And also, development status on PyPI is `2 - Pre-Alpha` - can you increase it to `5 - Production/Stable` maybe?

From my testing, `sorl-thumbnail==12.7.0` works with Django 3.1, 3.2, 4.0, and Python 3.9, 3.10.

**Comment by jayvdb** [comment]
The majority of this was done in https://github.com/jazzband/sorl-thumbnail/pull/682 , however PyPI metadata and docs still need an update.

See also https://github.com/jazzband/sorl-thumbnail/issues/675

**Comment by claudep** [comment]
This is done in master branch, so #675 is indeed the ticket to track now.

**Comment by uri-rodberg** [comment]
Django 4.0 and Python 3.9, 3.10 not supported on PyPI (sorl-thumbnail 12.8.0), although they are mentioned on https://github.com/jazzband/sorl-thumbnail/blob/master/CHANGES.rst.

**Comment by claudep** [comment]
Indeed, updating `setup.py` was forgotten, are you willing to make the corrective patch?

**Comment by uri-rodberg** [comment]
> Indeed, updating `setup.py` was forgotten, are you willing to make the corrective patch?

I can try. But you will need to release again. I'm not sure if that's possible with the same release version.

Do we still want to keep `'Development Status :: 2 - Pre-Alpha'`?

**Comment by claudep** [comment]
From the time the package exists, it should be noted as Stable IMHO. There is now a PR: #689
