### ISSUE TITLE
Use `extras_require` for optional dependencies.

### ISSUE THREAD

**Issue by gbdlin** [jazzband/sorl-thumbnail#684]
As `sorl-thumbnail` needs a separate imaging library for operation, it has to be installed separately. It is common to use another python library like pil, pillow or wand for that, but installing it and never explicitly using it in project may be confusing and may lead to accidental removal of them in the process of cleaning-up dependencies.

Allowing to install such backends together with `sorl-thumbnail` explicitly, using extras, so it is clear which package relies on its presence.

**Comment by Mogost** [comment]
I like the idea. Could you provide a PR for that?
