### ISSUE TITLE
Obsolete THUMBNAIL_KVSTORE

### ISSUE THREAD

**Issue by claudep** [jazzband/sorl-thumbnail#691]
I think that the configurable KVStore adds complexity to the project without real added value, all the more that now Django also includes a Redis cache backend in core. What about only keeping ``THUMBNAIL_CACHE`` to point to some Django-configured cache and tell users to do the cache configuration at the Django project level? 

Are there still use cases to implement/specify custom KVStores that are not possible as Django cache backends?

@camilonova, would love to get your input on this idea.

**Comment by camilonova** [comment]
Love it. Let's do it!
