### ISSUE TITLE
Is sorl-thumbnail pre-Alpha?

### ISSUE THREAD

**Issue by guettli** [jazzband/sorl-thumbnail#697]
According to this page the project is "pre-Alpha".

Is this correct?

https://djangopackages.org/packages/p/sorl-thumbnail/

**Comment by claudep** [comment]
See #690, someone has to review/approve the PR.

**Comment by uri-rodberg** [comment]
It looks like it has been defined as pre-alpha for the last 5 years by mistake. The next release, I hope, will be stable.

**Comment by claudep** [comment]
Fixed by #690.
