### ISSUE TITLE
Release a new version to PyPI - support Django 4.1 and Pillow 9.2.0.

### ISSUE THREAD

**Issue by uri-rodberg** [jazzband/sorl-thumbnail#698]
Hi,

I would like to see a new version of `sorl-thumbnail` on PyPI:

- Officially support Django 4.0, 4.1 and Python 3.9, 3.10 on PyPI.
- Remove `DeprecationWarning` with Pillow up to version 9.2.0 [https://github.com/jazzband/sorl-thumbnail/issues/695].

Commit https://github.com/jazzband/sorl-thumbnail/commit/8d7bd407be95f3dafdc2ad800b51194cada3599e should be included in the new version.

Currently, Pillow 9.0.1 is the last version supported by `sorl-thumbnail` without `DeprecationWarning`.

**Comment by claudep** [comment]
sorl-thumbnail is in need of at least a second active approved reviewer. Unless this happens, the module is stalled.

**Comment by claudep** [comment]
#690 at least must go in.

**Comment by claudep** [comment]
@uri-rodberg, are we ready now for the release?

**Comment by uri-rodberg** [comment]
> @uri-rodberg, are we ready now for the release?

@claudep I ran tests with the master branch of `sorl-thumbnail`, with `Pillow==9.2.0` and the tests are passing. But I didn't check in production or staging.

Will you be able to address this issue before you release a new version?
https://github.com/jazzband/sorl-thumbnail/issues/707

You can just rename `sorl-thumbnail/AUTHORS` to a format which supports links and make https://github.com/jazzband/sorl-thumbnail/graphs/contributors a link.

**Comment by claudep** [comment]
I tried to make a release by pushing a tag. Frankly, there are sooooooo many ways to make a release in packages nowadays that I'm confused if it's the right move for this package. @jezdez may help... ?

**Comment by uri-rodberg** [comment]
@claudep Try to change the tag to a release.

**Comment by claudep** [comment]
@jezdez, please can you see why tagging did not push the release on jazzband.io? The Release action succeeded, but the upload to Jazzband was not done for a mysterious reason.

**Comment by jezdez** [comment]
@claudep The release action for 12.9.0 did not run, since the workflow [is set up to only trigger when a GitHub release is created](https://github.com/jazzband/sorl-thumbnail/blob/d9d9a2b00b2c0c1a39153b80688ad2e8ab169553/.github/workflows/release.yml#L7-L9), not only when a tag is pushed.

I've just created https://github.com/jazzband/sorl-thumbnail/releases/tag/12.9.0 using the tag you created and the release workflow is now running: https://github.com/jazzband/sorl-thumbnail/actions/runs/2950435713

**Comment by claudep** [comment]
Thanks a lot @jezdez. Now I don't seem to be authorized to push releases to PyPI. May I ask you to do that, or else give me the appropriate permission?

**Comment by jezdez** [comment]
@claudep I've pushed the release, if you'd like to do this for sorl-thumbnail, you'd need to become co project lead, are you interested?

**Comment by claudep** [comment]
@jezdez, thanks for pushing!!
And yes I think you could add me to project leads (hopefully I'll not reach the burned-out threshold too quickly!)

@uri-rodberg Thanks for your patience!

**Comment by uri-rodberg** [comment]
@claudep Thank you for releasing `sorl-thumbnail` to PyPI.

@jezdez Thanks for your help!
