### ISSUE TITLE
Feature request: face detection or PPOI

### ISSUE THREAD

**Issue by h3x4git** [jazzband/sorl-thumbnail#700]
It would be great to guide the cropping process with some face detection algorithm or maybe just having a simple PPOI admin widget could help with the display of pictures uploaded by general users, so as to fix display problems

**Comment by uri-rodberg** [comment]
Face detection is done by AWS and I guess many other providers. I don't think `sorl-thumbnail` should detect faces.

**Comment by claudep** [comment]
I do agree with Uri, this is out of scope for `sorl-thumbnail`.

**Comment by h3x4git** [comment]
I was also mentioning PPOI though
