### ISSUE TITLE
Setting storage class does not support deconstructors

### ISSUE THREAD

**Issue by michjnich** [jazzband/sorl-thumbnail#712]
When setting the storage, sorl does not allow for a class instance being deconstructible, which is necessary to be able to use backends with arguments. 

### `sorl.thumbnails.images.py`
```
cls = self.storage._wrapped.__class__
```

For a deconstructible class this can use `self.storage.deconstruct` (checking whether the class is deconstructible first to ensure backwards compatibility). 

deserialize could check whether the storage is a list (deconstructible) or a single value (old method)

**Comment by claudep** [comment]
sorl-thumbnails now privileges a storage alias from the Django-configured STORAGES ([6fc7575]), so I guess this is no longer an issue.
