### ISSUE TITLE
DeprecationWarning from setuptools 67.5.0 and above

### ISSUE THREAD

**Issue by uri-rodberg** [jazzband/sorl-thumbnail#727]
Hi,

If `setuptools` 67.5.0 and above is installed, I receive a `DeprecationWarning` when running the tests with errors and warnings enabled (tested with Python 3.10.10):

```
  File "lib\site-packages\sorl\__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "lib\site-packages\pkg_resources\__init__.py", line 121, in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
DeprecationWarning: pkg_resources is deprecated as an API
```

With `setuptools` 67.4.0 and below, there is no `DeprecationWarning`.

**Comment by uri-rodberg** [comment]
https://setuptools.pypa.io/en/stable/history.html

**Comment by claudep** [comment]
If someone wants to work on this, the most straightforward replacement would be the point 5. of https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ (importlib.metadata)

**Comment by uri-rodberg** [comment]
> If someone wants to work on this, the most straightforward replacement would be the point 5. of https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ (importlib.metadata)

This code might work with Python >= 3.8

```
    from importlib.metadata import version

    __version__ = version("sorl-thumbnail")
```

It might be worth checking the Python version and/or running this code with try and then fail to what the code is doing right now:

```
from pkg_resources import get_distribution, DistributionNotFound

try:
    __version__ = get_distribution("sorl-thumbnail").version
except DistributionNotFound:
    pass
```

**Comment by uri-rodberg** [comment]
Actually, I see they also changed it already. Look at this code:

https://github.com/FactoryBoy/factory_boy/blob/master/factory/__init__.py#L73-L79

**Comment by claudep** [comment]
I'm sure you are now ready to suggest a PR :smile:

**Comment by uri-rodberg** [comment]
> I'm sure you are now ready to suggest a PR 😄

I'm not sure I can. Notice that `importlib_metadata` appears also in https://github.com/FactoryBoy/factory_boy/blob/master/setup.cfg as a required package. I would recommend adding  it as a required package for python_version<"3.8" and then using this code:

```
try:
    # Python 3.8+
    import importlib.metadata as importlib_metadata
except ImportError:
    import importlib_metadata

__version__ = importlib_metadata.version("sorl-thumbnail")
```

While replacing completely the current code (and not leaving it if the code fails).

**Comment by claudep** [comment]
That sounds like a plan!

**Comment by uri-rodberg** [comment]
Yes but I don't know how to add a required package. If you add it then you can just copy my code and out it on https://github.com/jazzband/sorl-thumbnail/blob/master/sorl/__init__.py.

**Comment by claudep** [comment]
In https://packaging.python.org/en/latest/guides/single-sourcing-package-version/, you'll find the explanation on how to add the conditional dependency.
