### ISSUE TITLE
Release new version to support Django 4.2

### ISSUE THREAD

**Issue by bpepple** [jazzband/sorl-thumbnail#730]
Noticed support for Django 4.2 has been committed, but no release has been released to PyPi.

**Comment by uri-rodberg** [comment]
> @uri-rodberg @claudep is there anything blocking a new release with the recent improvments?

@JanMalte I'm waiting for PR https://github.com/jazzband/sorl-thumbnail/pull/740 to be approved. But Regarding Django 4.2, it's not needed. I think if we release a new version now it should support Django 4.2.

**Comment by uri-rodberg** [comment]
Hi,

You can write in your requirements file the following line:

```
-e git+https://github.com/uri-rodberg/sorl-thumbnail.git@9339cc250328f7c5d00212877d920a69bf7e740a#egg=sorl_thumbnail
```

Or, manually run `pip install -e git+https://github.com/uri-rodberg/sorl-thumbnail.git@9339cc250328f7c5d00212877d920a69bf7e740a#egg=sorl_thumbnail`. This will install sorl-thumbnail from my fork with the updated commits (except one commit) and including my PR which is not merged yet. If you install this version, you can run it with Django 4.2.

**Comment by JanMalte** [comment]
@jezdez could you please step in and help to get a new release packed?

**Comment by claudep** [comment]
I wonder why noone proposed a patch to update the Changelog :roll_eyes:

**Comment by uri-rodberg** [comment]
> I wonder why noone proposed a patch to update the Changelog 🙄

Added support for Django 4.2.
Added support for Python 3.11.
Dropped support for Python 3.7.

And also, if you accept my PR (https://github.com/jazzband/sorl-thumbnail/pull/740), write something about it.

**Comment by claudep** [comment]
#746 for the CHANGES.rst updates.

**Comment by JanMalte** [comment]
@claudep @uri-rodberg if you are ok with the current master branch, I could try to make a new release.

**Comment by claudep** [comment]
Thanks @JanMalte ! I tried to trigger a release by pushing a tag, but as almost each package on which I contribute has a different release workflow, I don't remember if it was the right thing to do :disappointed:

**Comment by uri-rodberg** [comment]
> @claudep @uri-rodberg if you are ok with the current master branch, I could try to make a new release.

Hi @JanMalte. Actually I was hoping that my PR will be merged before the new release, but I understand we need to talk about it more, so I guess it's OK to release the master branch as it is now. I don't know how to release sorl-thumbnail, but good luck!

**Comment by claudep** [comment]
Oh, the release is now available on https://jazzband.co/projects/sorl-thumbnail, but I cannot push to PyPI as I'm not a project lead. Ping @jezdez or @camilonova

**Comment by jezdez** [comment]
@claudep Done.
