### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by koutoftimer** [jazzband/sorl-thumbnail#747]
https://sorl-thumbnail.readthedocs.io/en/latest/operation.html has broken link "[Schematic view of how things are done](https://docs.google.com/drawings/edit?id=1wlE4LkQpzXd2a2Nxfjt6_j5NG7889dzMyf0V-xPAJSE&hl=en)"

**Comment by claudep** [comment]
Duplicate of #714
