### ISSUE TITLE
Officially support Django 5.0 and Python 3.12 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [jazzband/sorl-thumbnail#753]
Django 5.0 and Python 3.12 are now in production. They should be supported on PyPi.

**Comment by claudep** [comment]
Fixed by 63866048f2031d237a8

**Comment by camilonova** [comment]
Done. https://pypi.org/project/sorl-thumbnail/

**Comment by uri-rodberg** [comment]
Thank you.
