### ISSUE TITLE
Release version 12.11.0 to PyPI

### ISSUE THREAD

**Issue by claudep** [jazzband/sorl-thumbnail#765]
@camilonova, @jezdez, the release is available on https://jazzband.co/projects/sorl-thumbnail

**Comment by claudep** [comment]
… or maybe put me in the lead team :nerd_face:

**Comment by camilonova** [comment]
Done https://pypi.org/project/sorl-thumbnail/

**Comment by claudep** [comment]
Thanks :heart: !
