### ISSUE TITLE
Upscale set to False seems to have an issue

### ISSUE THREAD

**Issue by reugene** [jazzband/sorl-thumbnail#78]
When generating a thumbnail with template tag and set upsacale to false 

  {% thumbnail photo.image "800x600" crop="center" upscale=False  as im %}
    <a href="{{im.url}}" rel="lightbox" title="{{im.caption}}">
  {% endthumbnail %}

If the image is smaller than 800x600 should remain the same but here the image came in 800x600 with the upscaled area filled with black color. 

view the resulting image below

  http://dl.dropbox.com/u/19286741/7e0d33a922b99a7e5e6e87e4813c86d9.jpeg

**Comment by camilonova** [comment]
This was fixed in #317
